import React from "react";

const Terms = () => {
    return (
        <div className="box">
            <div className="boxTitle">TERMS OF USE OF CRICKET FANTASY</div>
            <div className="boxContent">
                <h3>IMPORTANT! PLEASE CAREFULLY READ THESE TERMS OF USE BEFORE USING CRICKET FANTASY, AS THEY AFFECT YOUR LEGAL RIGHTS AND OBLIGATIONS.</h3><br/>
                <h3>PLEASE NOTE THAT APPLE DOES NOT SPONSOR OR INVOLVED IN ACTIVITY OF THIS APPLICATION IN ANY MANNER.</h3><br/>
                <h4>AGREEMENT</h4><br/>
                <p>CRICKET FANTASY owns and operates an application that links to these Terms of Use. We are pleased to offer you access to our application and the ability to participate in our fantasy sports challenges (collectively the "Services") that we may provide from our application, subject to these Terms of Use (the "Terms of Use", or “Terms”), our privacy policy (the "Privacy Policy") and the Official Rules and Regulations for the applicable challenges and promotions (the "Rules" and together with the Terms of Use and the Privacy Policy). </p><br/>
                <h4>CONSENT</h4><br/>
                <p>You agree to these Terms of Use by accessing or using Application, registering for Services offered, or by accepting, uploading, submitting or downloading any information or content from or to the Application.</p><br/>
                <p><strong>IF YOU DO NOT AGREE TO BE BOUND BY ALL OF THESE TERMS OF USE, DO NOT USE THE APPLICATION. </strong></p><br/>
                <p>These Terms of Use constitute a legal agreement between you and CRICKET FANTASY, and shall apply to your use of the Application and the Services even after termination.</p><br/>
                <h4>ELIGIBILITY</h4><br/>
                <p>In order to use our Service, you may be required to register a user account (“Account”). In this case, you agree to provide and undertake most exact information when requested:</p><br/>
                <ol>
                    <li>You are at a legal capacity to use our Service.</li>
                    <li>You will abide at all times by these Terms of Use, as amended, and any other agreements between you and CRICKET FANTASY regarding your use of our Service. </li>
                    <li>You have not previously had an Account which was closed due to failure to comply with these Terms of Use. </li>
                    <li>you are at least 17 years of age or more. </li>
                    <li>We reserve the right to request documentation for your information at all times, including, but not limited to, proof of age, identity and address. Should that you fail to provide this information we reserve the right to close or suspend your Account.</li>
                </ol><br/>
                <h4>CONDITIONS OF APP USAGE</h4><br/>
                <p>By entering a Challenge, entrants agree to be bound by these Rules and the decisions of CRICKET FANTASY, which shall be final and binding in all respects. The Company, at its sole discretion, may disqualify any entrant from a Challenge, if the entrant engages in conduct or otherwise utilizes any information the Company deems to be improper, unfair or otherwise adverse to the operation of the Challenge or is in any way detrimental to other entrants.</p><br/>
                <p>In addition, conduct that would be deemed improper also includes, but is not limited to: </p><br/>
                <ul>
                    <li>Falsifying personal information required to enter a Challenge; </li>
                    <li>Any violation of Game rules or the Terms of Use;</li>
                    <li>Obtaining other entrants information and spamming other entrants; or </li>
                    <li>Abusing the Application in any way.</li>
                </ul><br/>
                <p>CRICKET FANTASY is not responsible for: any incorrect, invalid or inaccurate entry information; human errors; postal delays/postage due mail; technical malfunctions; failures, including public utility or telephone outages; omissions, interruptions, deletions or defects of any telephone system or network, computer online systems, data, computer equipment, servers, providers, or software (including, but not limited to software and operating systems that do not permit an entrant to participate in a Challenge), including without limitation any injury or damage to any entrant's or any other person's computer or video equipment relating to or resulting from participation in a Challenge; inability to access the Application, or any pages that are part of or related to the Application; theft, tampering, destruction, or unauthorized access to, or alteration of, entries and/or images of any kind; data that is processed late or incorrectly or is incomplete or lost due to telephone, postal issues, computer or electronic malfunction or traffic congestion on telephone lines or transmission systems, or the Internet, or any service provider's facilities, or any phone site or website or for any other reason whatsoever; typographical, printing or other errors, or any combination thereof. </p><br/>
                <h4>TERMINATION AND EFFECT OF TERMINATION</h4><br/>
                <p>In addition to any other legal or equitable remedy, CRICKET FANTASY may, without prior notice, immediately revoke any or all of your rights granted hereunder. In such event, you will immediately cease all access to and use of the CRICKET FANTASY application. CRICKET FANTASY may revoke any password(s) and/or account identification issued to you and deny you access to and use of the application. Any such action shall not affect any rights and obligations arising prior thereto. All provisions of the Terms of Use which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p><br/>
                <h4>ADDITIONAL TERMS FOR APPLE (IOS APPLICATION)</h4><br/>
                <p>You agree and acknowledge that these Terms are binding between you and CRICKET FANTASY only, and Apple is not a part of it, it is CRICKET FANTASY that is responsible for the app and the content thereof. Apple is not associated with the game and is not a sponsor. You must use the iOS app only on an Apple product that runs iOS. Your use of the app must comply with the terms of use applicable to the Apple source from which you obtain it (including the <strong>Usage Rules set forth in the Apple App Store Terms of Service</strong>). You acknowledge that Apple has no obligation to provide you any maintenance and support services with respect to the app. You acknowledge that Apple is not responsible for addressing any claims you have or any claims of any third party relating to the app or your possession and use of the app, including, but not limited to product warranty or liability claims; any claim that the app fails to conform to any applicable legal or regulatory requirement; claims arising under consumer protection or similar legislation; or claims that the app infringes a third party’s intellectual property rights. Apple, and Apple’s subsidiaries, are third-party beneficiaries of these Terms. Upon your acceptance of the Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce the Terms against you as a third party beneficiary thereof. There are no other third-party beneficiaries of the Terms.</p><br/>
                <h4>WARRANTY DISCLAIMERS</h4><br/>
                <p>THE APPLICATION, INCLUDING, WITHOUT LIMITATION, ALL CONTENT, SOFTWARE, AND FUNCTIONS MADE AVAILABLE ON OR ACCESSED THROUGH OR SENT FROM THE APPLICATION, ARE PROVIDED "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS." TO THE FULLEST EXTENT PERMISSIBLE BY LAW, THE COMPANY AND ITS PARENTS, SUBSIDIARIES AND AFFILIATES MAKE NO REPRESENTATION OR WARRANTIES OR ENDORSEMENTS OF ANY KIND WHATSOEVER (EXPRESS OR IMPLIED) ABOUT: (A) THE APPLICATION; (B) THE FUNCTIONS MADE ACCESSIBLE ON OR ACCESSED THROUGH THE APPLICATION; (C) ANY PRODUCTS OR SERVICES OFFERED VIA THE APPLICATION OR HYPERTEXT LINKS TO THIRD PARTIES; AND/OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION THROUGH APPLICATION. THE COMPANY DOES NOT WARRANT THAT THE APPLICATION, ANY OF THE APPLICATION'S FUNCTIONS OR ANY CONTENT CONTAINED THEREIN WILL BE UNINTERRUPTED OR ERROR-FREE; THAT DEFECTS WILL BE CORRECTED; OR THAT THE APPLICATION OR THE SERVERS THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p><br/>
                <p>THE COMPANY DOES NOT WARRANT THAT YOUR ACTIVITIES OR USE OF THE APPLICATION IS LAWFUL IN ANY PARTICULAR JURISDICTION AND, IN ANY EVENT, THE COMPANY SPECIFICALLY DISCLAIMS SUCH WARRANTIES. YOU UNDERSTAND THAT BY USING ANY OF THE FEATURES OF APPLICATION, YOU ACT AT YOUR OWN RISK, AND YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE APPLICATION.</p>
                <h4>LIMITED LIABILITY</h4><br/>
                <p>YOU UNDERSTAND AND AGREE THAT CRICKET FANTASY SHALL HAVE NO RESPONSIBILITY OR LIABILITY FOR ANY DIRECT OR INDIRECT DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF WE HAD BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE OUR SERVICE; (ii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OF DATA; (iii) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (iv) ANY OTHER MATTER RELATING TO OUR SERVICE. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, CRICKET FANTASY LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO CRICKET FANTASY FOR GENERAL USE OF OUR SERVICE DURING THE TERM OF YOUR REGISTRATION. WE SHALL HAVE NO RESPONSIBILITY OR LIABILITY FOR ANY CONTENT APPEARING ON YOUR WEB SITE. YOU AGREE TO INDEMNIFY AND DEFEND US AGAINST ALL CLAIMS ARISING OUT OF OR BASED UPON THE USE OF OUR SERVICE.</p><br/>
                <h4>INTELLECTUAL PROPERTY RIGHTS</h4><br/>
                <p>The content on the Application, including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like and the trademarks, service marks and logos contained therein (the "Intellectual Property"), are owned by or licensed to CRICKET FANTASY, subject to copyright and other intellectual property rights. Content on the Application is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. CRICKET FANTASY reserves all rights not expressly granted in and to the Application and the Intellectual Property. You agree to not engage in the use, copying, or distribution of any of the Intellectual Property other than expressly permitted herein. If you download or print a copy of the Intellectual Property for personal use, you must retain all copyright and other proprietary notices contained therein. You agree not to circumvent, disable or otherwise interfere with security related features of the Application or its features that prevent or restrict use or copying of any Intellectual Property or enforce limitations on use of the Application or the Intellectual Property therein. </p><br/>
                <p>You represent and warrant that you have all rights necessary to grant to CRICKET FANTASY the license above and that none of your User Submissions are defamatory, violate any rights of third parties (including intellectual property rights or rights of publicity or privacy), or violate applicable law.</p>
            </div>
        </div>
    );
};

export default Terms;
